### ISSUE TITLE
creation of Discount field crashed discound field view 

### ISSUE THREAD

**Issue by Jocky92** [liedekef/events-made-easy#189]
i created a new discound field. i used chars like _ and -
after create the field i cannot more load and see all other discount filelds at the overview list. the list is shown empty and i get the message: "Error: An error occured while communicating to the server."
i can still create more discount fields. When i open an event i can select the field so the field should be created.

its now not longer possible to edit any discount field because the overview showes empty

**Comment by liedekef** [comment]
I just created the discount named '_ and - # &$;' and no problem at all.
If this error happens, something unexpected is coming back in the output (the content of the table is loaded via an ajax call). Check your browser console and network when loading the content of the discount overview. If unsure: feel free to provide me with a temp account so I can check on your end.

**Comment by Jocky92** [comment]
hm okay i thought this should be the problem with _ or - but maybe not.

under Network i only can see this name:
admin-ajax.php?action=eme_discounts_list&jtStartIndex=0&jtPageSize=500&jtSorting=name%20ASC

status: 500
with this response:
<p>Es gab einen kritischen Fehler auf deiner Website.</p>
<p>
    <a href="https://wordpress.org/documentation/article/faq-troubleshooting/">Erfahre mehr über die Problembehandlung in WordPress.</a>
</p>

otherwise i could create you a temp account maybe thats easyer for you?

**Comment by liedekef** [comment]
Check your php error logs, in this. ASE those should mention what went wrong.
Also make sure you are using the latest version

**Comment by liedekef** [comment]
And what is your EME version? I see 1 error related to EME but that was fixed some versions ago.

**Comment by liedekef** [comment]
Currently I'm going to file this as closed, updating to the latest version should fix this.

**Comment by Jocky92** [comment]
im using Version: 2.3.5. There is no newer version and i have still the
issue with the error and the empty table.

Am So., 4. Juni 2023 um 22:17 Uhr schrieb Franky Van Liedekerke <
***@***.***>:

**Comment by liedekef** [comment]
Since you're on github, you must have read the post on that. Go to the main page here: https://github.com/liedekef/events-made-easy , and in the readme section on that page, read the part 'for existing wordpress users'. You need to update immediately.

**Comment by Jocky92** [comment]
i am so sorry i did not notice that. i updated to the newest version but
still have the bug and cannot see the discount table.

Am Mo., 5. Juni 2023 um 11:05 Uhr schrieb Franky Van Liedekerke <
***@***.***>:

**Comment by liedekef** [comment]
The newest version can't possibly have that bug. The code changed etc ...  please check your logs again (and make sure no browser cache is interfering).
