### ISSUE TITLE
Inconsistent map display

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#671]
**Describe the bug**
In the administration, the locations are well defined, with precise address and contact details. The map is displayed correctly. But in the form for programming an event, the map displays a location abroad that has nothing to do with the one indicated in the location database. However, the location in the form is chosen from the list of locations.
**To Reproduce**
You need to have admin rights to check this

**Expected behavior**
The maps should be the same

**Screenshots**
Location sceenshot
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/ebaa38ba-b31b-4fff-94ec-0a60efe60f60">

Event frontend submit
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/5b97d1b3-4e7a-4c3c-a6d5-c4c920f67f98">

**Online Demo**
You need to have admin rights to check this
**Log output*
php error logfile and add php errors here 
```
[11-Nov-2024 18:46:30 UTC] PHP Warning:  Undefined variable $scope in /home/taeq4768/vogue-et-reve.fr/wp-content/extens/events-made-easy/eme-locations.php on line 1632
[11-Nov-2024 18:46:30 UTC] PHP Warning:  Undefined variable $width in /home/taeq4768/vogue-et-reve.fr/wp-content/extens/events-made-easy/eme-locations.php on line 1642
```
**Version info**
PHP version: 8.3
EME version: 2.5.15 (I never had this problem before this version)

**Additional context**
On the create event page the shortcode is [eme_add_event_form id=72]
And the form id=72 is : 

```
Information du voilier (ne saisir que les 2 ou 3  premières lettres puis choisir dans la liste)

Nom du voilier
#REQ_FIELD{location_name}
Lieu
#_FIELD{location_address1}
Ville
#_FIELD{location_city}
#_MAP
#_SUBMIT{Publier ma navigation}
```

**Comment by liedekef** [comment]
The php warnings should be fixed here:
https://github.com/liedekef/events-made-easy/commit/2ce8a2310bc64855b9518edb366757f3ce2259dd

I'll need to test the frontend code (later)

**Comment by liedekef** [comment]
Concerning the frontend form and the map: I can reproduce this, but I am only able to fix that this evening.

**Comment by liedekef** [comment]
For the map, please check this fix:
https://github.com/liedekef/events-made-easy/commit/e82979af73601d3650c2a8a06601a5b502298d18

**Comment by f14m07** [comment]
Well. I have uploaded the three files : eme_location.php and the two js files for map.
But the issue is still present.
Also this other error log: 
```
[12-Nov-2024 10:32:08 UTC] PHP Warning:  Undefined variable $scope in /home/taeq4768/vogue-et-reve.fr/wp-content/extens/events-made-easy/eme-locations.php on line 1632
[12-Nov-2024 10:32:08 UTC] PHP Warning:  Undefined variable $width in /home/taeq4768/vogue-et-reve.fr/wp-content/extens/events-made-easy/eme-locations.php on line 1642
[12-Nov-2024 14:51:06 UTC] PHP Warning:  Undefined variable $scope in /home/taeq4768/vogue-et-reve.fr/wp-content/extens/events-made-easy/eme-locations.php on line 1632
[12-Nov-2024 14:51:06 UTC] PHP Warning:  Undefined variable $width in /home/taeq4768/vogue-et-reve.fr/wp-content/extens/events-made-easy/eme-locations.php on line 1642
[12-Nov-2024 16:58:44 UTC] PHP Warning:  Undefined variable $width in /home/taeq4768/vogue-et-reve.fr/wp-content/extens/events-made-easy/eme-locations.php on line 1643
[12-Nov-2024 16:58:44 UTC] PHP Warning:  Undefined variable $height in /home/taeq4768/vogue-et-reve.fr/wp-content/extens/events-made-easy/eme-locations.php on line 1643
[12-Nov-2024 17:02:35 UTC] PHP Warning:  Undefined variable $width in /home/taeq4768/vogue-et-reve.fr/wp-content/extens/events-made-easy/eme-locations.php on line 1643
[12-Nov-2024 17:02:35 UTC] PHP Warning:  Undefined variable $height in /home/taeq4768/vogue-et-reve.fr/wp-content/extens/events-made-easy/eme-locations.php on line 1643
[12-Nov-2024 17:05:25 UTC] PHP Warning:  Undefined variable $width in /home/taeq4768/vogue-et-reve.fr/wp-content/extens/events-made-easy/eme-locations.php on line 1643
[12-Nov-2024 17:05:25 UTC] PHP Warning:  Undefined variable $height in /home/taeq4768/vogue-et-reve.fr/wp-content/extens/events-made-easy/eme-locations.php on line 1643
```

**Comment by liedekef** [comment]
Sure you used the latest files from github? Because the php-line numbers in your errors don't match the ones in github.
Also for the js: make sure to do a ctrl-refresh (or clear cache).

**Comment by f14m07** [comment]
Well. I have uploaded the zip of the dev version on my local site (no cache there) and replace all the file of the EME version 2.5.15.
When I test the form, I have the right map on the screen during a very short time and just immediately the wrong map appear.

**Comment by f14m07** [comment]
Excuse-me. Now it's good. I had forgotten the safari cache

**Comment by liedekef** [comment]
and the php warnings gone too?

**Comment by f14m07** [comment]
No new php warnings at that moment
