### ISSUE TITLE
sumup gateway error

### ISSUE THREAD

**Issue by dfunnell1** [liedekef/events-made-easy#79]
**Describe the bug**
When going to the payment page; i get the following error:

`Fatal error: Uncaught ValueError: Path cannot be empty in /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/payment_gateways/sumup/vendor/sumup/sumup-ecom-php-sdk/src/SumUp/Utils/Headers.php:71 Stack trace: #0 /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/payment_gateways/sumup/vendor/sumup/sumup-ecom-php-sdk/src/SumUp/Utils/Headers.php(71): file_get_contents('') #1 /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/payment_gateways/sumup/vendor/sumup/sumup-ecom-php-sdk/src/SumUp/Utils/Headers.php(59): SumUp\Utils\Headers::getProjectVersion() #2 /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/payment_gateways/sumup/vendor/sumup/sumup-ecom-php-sdk/src/SumUp/Utils/Headers.php(87): SumUp\Utils\Headers::getTrk() #3 /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/payment_gateways/sumup/vendor/sumup/sumup-ecom-php-sdk/src/SumUp/Services/Authorization.php(140): SumUp\Utils\Headers::getStandardHeaders() #4 /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/payment_gateways/sumup/vendor/sumup/sumup-ecom-php-sdk/src/SumUp/Services/Authorization.php(83): SumUp\Services\Authorization->getTokenByClientCredentials() #5 /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/payment_gateways/sumup/vendor/sumup/sumup-ecom-php-sdk/src/SumUp/SumUp.php(57): SumUp\Services\Authorization->getToken() #6 /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/eme-payments.php(879): SumUp\SumUp->__construct(Array) #7 /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/eme-payments.php(333): eme_sumup_form('Adult Annual', Array, '17', 'GBP', 0) #8 /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/eme-payments.php(53): eme_payment_member_form('36', 0, 1) #9 /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/eme-events.php(1252): eme_payment_form('36', 0, 1) #10 /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/eme-events.php(1396): eme_events_page_content() #11 /homepages/13/d4296847737/htdocs/wordpress/wp-includes/class-wp-hook.php(308): eme_filter_events_page('\n<p></p>\n\n\n\n<p>...') #12 /homepages/13/d4296847737/htdocs/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters('\n<p></p>\n\n\n\n<p>...', Array) #13 /homepages/13/d4296847737/htdocs/wordpress/wp-includes/post-template.php(255): apply_filters('the_content', '<!-- wp:paragra...') #14 /homepages/13/d4296847737/htdocs/wordpress/wp-content/themes/fluid-basics/template-parts/content-single.php(42): the_content() #15 /homepages/13/d4296847737/htdocs/wordpress/wp-includes/template.php(785): require('/homepages/13/d...') #16 /homepages/13/d4296847737/htdocs/wordpress/wp-includes/template.php(718): load_template('/homepages/13/d...', false, Array) #17 /homepages/13/d4296847737/htdocs/wordpress/wp-includes/general-template.php(204): locate_template(Array, true, false, Array) #18 /homepages/13/d4296847737/htdocs/wordpress/wp-content/themes/responsiveblogily/page.php(23): get_template_part('template-parts/...', 'single') #19 /homepages/13/d4296847737/htdocs/wordpress/wp-includes/template-loader.php(106): include('/homepages/13/d...') #20 /homepages/13/d4296847737/htdocs/wordpress/wp-blog-header.php(19): require_once('/homepages/13/d...') #21 /homepages/13/d4296847737/htdocs/wordpress/index.php(17): require('/homepages/13/d...') #22 {main} thrown in /homepages/13/d4296847737/htdocs/wordpress/wp-content/plugins/events-made-easy/payment_gateways/sumup/vendor/sumup/sumup-ecom-php-sdk/src/SumUp/Utils/Headers.php on line 71`

**To Reproduce**
complete new membership form. when redirected to payment gateway for sumup either automatically or by clicking button, the error above with appear.

**Expected behavior**
sumup payment gateway should display

**Screenshots**
![image](https://user-images.githubusercontent.com/99143338/221421615-288815ef-f37f-4989-88a0-7b0fd56ccc3d.png)
![image](https://user-images.githubusercontent.com/99143338/221421619-1cb93256-6ab3-472a-a461-b03d752f8b4e.png)

**Log output**
If applicable, check your php error logfile and add php errors here

**Additional context**

**Comment by liedekef** [comment]
apparently sumup looks at composer.json for version info, but I excluded that from the release zip. I now released a new version that includes it.

**Comment by dfunnell1** [comment]
Hi Frankie, Thank you for looking into this, however this does seem to have fixed this error. I have updated the plugin via wordpress, flushed the cache and tried again and the same error appears. I have then tried downloading the plugin again from github and uploading it to wordpress, still no change.

**Comment by liedekef** [comment]
Ah ... I accidentally added the composer.lock to the zip, not the composer.json
To fix your issue: download composer.json from the code: https://github.com/liedekef/events-made-easy/tree/main/payment_gateways/sumup
and put the file in events-made-easy/payment_gateways/sumup

**Comment by liedekef** [comment]
Btw: I now also updated the latest release with the corrected zip
